# Generated by Django 5.0.6 on 2024-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sev_title', models.CharField(max_length=50)),
                ('ser_dec', models.TextField()),
            ],
        ),
    ]
