# Generated by Django 5.0.6 on 2024-06-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.TextField()),
                ('email1', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=100)),
            ],
        ),
    ]
#model is converted but wet not create table for creating table we have to use make migrate