# Generated by Django 5.0.6 on 2024-06-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_register_quiz_alter_signup_email1_alter_signup_name1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_quiz',
            name='Collage',
            field=models.CharField(blank=True, choices=[('Anjuman Engg', 'Anjuman Engg'), ('Anjuman Poly', 'Anjuman Poly'), ('Other', 'Other')], max_length=100, null=True),
        ),
        
    ]
